spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/vendi-dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

# JWT para Desenvolvimento
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 28800000

google:
  cloud:
    storage:
      bucket-name: ${GOOGLE_CLOUD_BUCKET_NAME:vendi-pdv}
      credentials: ${GOOGLE_CLOUD_CREDENTIALS:}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.vendi: DEBUG
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
