spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

server:
  port: ${PORT:8080}

google:
  cloud:
    storage:
      bucket-name: ${GOOGLE_CLOUD_BUCKET_NAME:vendi-pdv}
      credentials: ${GOOGLE_CLOUD_CREDENTIALS}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.vendi: INFO
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when-authorized
